#!/bin/bash

# Enhanced setup script for Pioneer ROS system with full configuration support
# This script configures the system using ALL settings from the central config file

set -e  # Exit on any error

CONFIG_FILE="config/system_config.yaml"
CONFIG_DEFAULT="config/system_config.yaml.default"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_DIR="$(dirname "$SCRIPT_DIR")"

# Function to check and create config file from template
setup_config_file() {
    if [ ! -f "$CONFIG_FILE" ]; then
        if [ -f "$CONFIG_DEFAULT" ]; then
            echo "=========================================="
            echo "FIRST TIME SETUP DETECTED"
            echo "=========================================="
            echo "Creating local configuration from template..."
            cp "$CONFIG_DEFAULT" "$CONFIG_FILE"
            echo "Created $CONFIG_FILE from template."
            echo ""
            echo "IMPORTANT: Please edit $CONFIG_FILE with your robot-specific settings:"
            echo "  - robot.id: Your robot ID (p1, p2, p3, etc.)"
            echo "  - user.name: Your username"
            echo "  - user.home_dir: Your home directory"
            echo ""
            echo "After editing, run this script again to continue setup."
            echo "=========================================="
            exit 0
        else
            echo "Error: Neither $CONFIG_FILE nor $CONFIG_DEFAULT found!"
            echo "Cannot proceed without configuration."
            exit 1
        fi
    else
        # Check if template is newer than local config
        if [ -f "$CONFIG_DEFAULT" ] && [ "$CONFIG_DEFAULT" -nt "$CONFIG_FILE" ]; then
            echo "WARNING: Template configuration is newer than your local configuration."
            echo "New features may have been added. Consider reviewing:"
            echo "  diff $CONFIG_FILE $CONFIG_DEFAULT"
            echo ""
        fi
    fi
}

# Set up configuration file
setup_config_file

# Function to setup udev rules for USB devices
setup_udev_rules() {
    echo "Setting up udev rules for USB devices..."
    
    UDEV_RULES_FILE="/etc/udev/rules.d/99-pioneer-usb.rules"
    TEMP_RULES_FILE="/tmp/99-pioneer-usb.rules"
    
    # Create udev rules content
    cat > "$TEMP_RULES_FILE" << 'EOF'
# Pioneer ROS USB device rules
# Auto-generated by setup.sh - DO NOT EDIT MANUALLY

# udev rule for GPS device (CP210x)
SUBSYSTEM=="tty", ATTRS{idVendor}=="10c4", ATTRS{idProduct}=="ea60", SYMLINK+="gps", MODE="0666"

# udev rule for XBee RF module
SUBSYSTEM=="tty", ATTRS{idVendor}=="0403", ATTRS{idProduct}=="6015", SYMLINK+="xbee", MODE="0666"
EOF

    # Check if rules need to be updated
    if [ -f "$UDEV_RULES_FILE" ]; then
        if ! diff -q "$TEMP_RULES_FILE" "$UDEV_RULES_FILE" > /dev/null 2>&1; then
            echo "Updating udev rules..."
            sudo cp "$TEMP_RULES_FILE" "$UDEV_RULES_FILE"
            UDEV_UPDATED=true
        else
            echo "Udev rules are already up to date."
            UDEV_UPDATED=false
        fi
    else
        echo "Creating new udev rules..."
        sudo cp "$TEMP_RULES_FILE" "$UDEV_RULES_FILE"
        UDEV_UPDATED=true
    fi
    
    rm -f "$TEMP_RULES_FILE"
    
    # Reload udev rules if updated
    if [ "$UDEV_UPDATED" = true ]; then
        echo "Reloading udev rules..."
        sudo udevadm control --reload-rules
        sudo udevadm trigger --subsystem-match=tty
        echo "Udev rules installed successfully."
        echo "USB devices will now have consistent names:"
        echo "  - GPS device (CP210x): /dev/gps"
        echo "  - XBee module: /dev/xbee"
        echo ""
    fi
}

# Setup udev rules before continuing
setup_udev_rules

# Function to read YAML values
read_yaml() {
    local file=$1
    local key=$2
    python3 -c "
import yaml
import sys
import re

try:
    with open('$file', 'r') as f:
        data = yaml.safe_load(f)
    path = '$key'
    
    # Split key path by dot, but handle indices like 'foo[0]'
    keys = []
    for part in path.split('.'):
        match = re.findall(r'([^\[\]]+)|\[(\d+)\]', part)
        for name, index in match:
            if name:
                keys.append(name)
            elif index:
                keys.append(int(index))

    value = data
    for k in keys:
        value = value[k]

    if isinstance(value, bool):
        print(str(value).lower())
    else:
        print(value)
except Exception as e:
    print('', file=sys.stderr)
    sys.exit(1)
"
}

# Check if config file exists
if [ ! -f "$CONFIG_FILE" ]; then
    echo "Error: Configuration file $CONFIG_FILE not found"
    echo "Please create the configuration file first"
    exit 1
fi

# Read all configuration values
ROBOT_ID=$(read_yaml "$CONFIG_FILE" "robot.id")
USER_NAME=$(read_yaml "$CONFIG_FILE" "user.name")
HOME_DIR=$(read_yaml "$CONFIG_FILE" "user.home_dir")
WORK_DIR="$HOME_DIR/ros2_ws"

# Read GPS configuration
GPS_BAUDRATE=$(read_yaml "$CONFIG_FILE" "gps.baudrate")
GPS_TIMEOUT=$(read_yaml "$CONFIG_FILE" "gps.timeout")
GPS_CONNECTION_TIMEOUT=$(read_yaml "$CONFIG_FILE" "gps.connection_timeout")
GPS_RETRY_DELAY=$(read_yaml "$CONFIG_FILE" "gps.retry_delay")
GPS_MOVING_AVG_RATE=$(read_yaml "$CONFIG_FILE" "gps.moving_average_rate")
GPS_UPDATE_RATE=$(read_yaml "$CONFIG_FILE" "gps.update_rate" || echo "1.0")
GPS_TIMER_PERIOD=$(read_yaml "$CONFIG_FILE" "gps.timer_period" || echo "1.0")

# Read GPS device paths as array
GPS_DEVICE_PATHS=""
device_count=0
while true; do
    device_path=$(read_yaml "$CONFIG_FILE" "gps.device_paths[$device_count]" 2>/dev/null || echo "")
    if [ -z "$device_path" ]; then
        break
    fi
    if [ -z "$GPS_DEVICE_PATHS" ]; then
        GPS_DEVICE_PATHS="\"$device_path\""
    else
        GPS_DEVICE_PATHS="$GPS_DEVICE_PATHS, \"$device_path\""
    fi
    device_count=$((device_count + 1))
done

# Default device paths if none specified
if [ -z "$GPS_DEVICE_PATHS" ]; then
    GPS_DEVICE_PATHS='"/dev/ttyUSB0", "/dev/ttyUSB1", "/dev/ttyACM0", "/dev/ttyACM1", "/dev/gps"'
fi

# Read IMU configuration
IMU_HEADING_OFFSET=$(read_yaml "$CONFIG_FILE" "imu.heading_offset")
IMU_CONNECTION_TIMEOUT=$(read_yaml "$CONFIG_FILE" "imu.connection_timeout")
IMU_RETRY_DELAY=$(read_yaml "$CONFIG_FILE" "imu.retry_delay")
IMU_CALIBRATION_FILE=$(read_yaml "$CONFIG_FILE" "imu.calibration_file")
IMU_PUBLISH_RATE=$(read_yaml "$CONFIG_FILE" "imu.publish_rate" || echo "20.0")
IMU_ENABLE_EXTENDED=$(read_yaml "$CONFIG_FILE" "imu.enable_extended_output" || echo "true")
IMU_ENABLE_LEGACY=$(read_yaml "$CONFIG_FILE" "imu.enable_legacy_compatibility" || echo "true")

# Validate IMU parameters
if ! echo "$IMU_PUBLISH_RATE" | grep -E '^[0-9]+(\.[0-9]+)?$' > /dev/null; then
    echo "Error: IMU publish_rate must be a positive number, got '$IMU_PUBLISH_RATE'"
    exit 1
fi

if ! echo "$IMU_ENABLE_EXTENDED" | grep -E '^(true|false)$' > /dev/null; then
    echo "Error: IMU enable_extended_output must be true or false, got '$IMU_ENABLE_EXTENDED'"
    exit 1
fi

if ! echo "$IMU_ENABLE_LEGACY" | grep -E '^(true|false)$' > /dev/null; then
    echo "Error: IMU enable_legacy_compatibility must be true or false, got '$IMU_ENABLE_LEGACY'"
    exit 1
fi

# Read RF Receiver configuration
RF_BAUDRATE=$(read_yaml "$CONFIG_FILE" "rf_receiver.baudrate")
RF_RETRY_DELAY=$(read_yaml "$CONFIG_FILE" "rf_receiver.retry_delay")
RF_RETRY_ATTEMPTS=$(read_yaml "$CONFIG_FILE" "rf_receiver.retry_attempts")
RF_UPDATE_RATE=$(read_yaml "$CONFIG_FILE" "rf_receiver.update_rate")
RF_TIMER_PERIOD=$(read_yaml "$CONFIG_FILE" "rf_receiver.timer_period")

# Read RF device paths as array
RF_DEVICE_PATHS=""
device_count=0
while true; do
    device_path=$(read_yaml "$CONFIG_FILE" "rf_receiver.device_paths[$device_count]" 2>/dev/null || echo "")
    if [ -z "$device_path" ]; then
        break
    fi
    if [ -z "$RF_DEVICE_PATHS" ]; then
        RF_DEVICE_PATHS="\"$device_path\""
    else
        RF_DEVICE_PATHS="$RF_DEVICE_PATHS, \"$device_path\""
    fi
    device_count=$((device_count + 1))
done

# Default device paths if none specified (xbee only)
if [ -z "$RF_DEVICE_PATHS" ]; then
    RF_DEVICE_PATHS='"/dev/xbee"'
fi

# Read Locomotion configuration
LOCOMOTION_MAX_VEL=$(read_yaml "$CONFIG_FILE" "locomotion.max_velocity")
LOCOMOTION_MAX_VEL_OPEN=$(read_yaml "$CONFIG_FILE" "locomotion.max_velocity_open")
LOCOMOTION_SERIAL_PORT=$(read_yaml "$CONFIG_FILE" "locomotion.serial_port")
LOCOMOTION_BAUDRATE=$(read_yaml "$CONFIG_FILE" "locomotion.baudrate")
LOCOMOTION_LEFT_MOTOR_SIGN=$(read_yaml "$CONFIG_FILE" "locomotion.left_motor_sign")
LOCOMOTION_RIGHT_MOTOR_SIGN=$(read_yaml "$CONFIG_FILE" "locomotion.right_motor_sign")

# Read Battery monitoring configuration
BATTERY_ENABLED=$(read_yaml "$CONFIG_FILE" "locomotion.battery_monitoring.enabled" || echo "true")
BATTERY_UPDATE_INTERVAL=$(read_yaml "$CONFIG_FILE" "locomotion.battery_monitoring.update_interval" || echo "1.0")

# Read Pose converter configuration
POSE_TIMER_PERIOD=$(read_yaml "$CONFIG_FILE" "pose_converter.timer_period")
POSE_HEALTH_CHECK_PERIOD=$(read_yaml "$CONFIG_FILE" "pose_converter.health_check_period")
POSE_RESET_TIMEOUT=$(read_yaml "$CONFIG_FILE" "pose_converter.reset_timeout")

# Read Monitoring configuration
MONITOR_SENSOR_TIMEOUT=$(read_yaml "$CONFIG_FILE" "monitoring.sensor_timeout")
MONITOR_MAX_RETRIES=$(read_yaml "$CONFIG_FILE" "monitoring.max_node_retries")
MONITOR_RESTART_DELAY=$(read_yaml "$CONFIG_FILE" "monitoring.node_restart_delay")

RF_PUB_TOPIC=$(read_yaml "$CONFIG_FILE" "rf_receiver.pub_topic")

if [ -z "$ROBOT_ID" ] || [ -z "$USER_NAME" ] || [ -z "$HOME_DIR" ]; then
    echo "Error: Failed to read required configuration values"
    echo "Please check your configuration file: $CONFIG_FILE"
    exit 1
fi

echo "Setting up system for:"
echo "  Robot ID: $ROBOT_ID"
echo "  User: $USER_NAME"
echo "  Home Directory: $HOME_DIR"
echo "  Workspace: $WORK_DIR"
echo ""
echo "Configuration loaded:"
echo "  GPS: baudrate=$GPS_BAUDRATE, timeout=$GPS_TIMEOUT, update_rate=${GPS_UPDATE_RATE}Hz"
echo "  GPS Device Paths: [$GPS_DEVICE_PATHS]"
echo "  IMU: heading_offset=$IMU_HEADING_OFFSET, publish_rate=${IMU_PUBLISH_RATE}Hz, extended=$IMU_ENABLE_EXTENDED"
echo "  Locomotion: max_vel=$LOCOMOTION_MAX_VEL, battery_monitoring=$BATTERY_ENABLED"
echo "  Monitoring: sensor_timeout=$MONITOR_SENSOR_TIMEOUT"

# Create necessary directories
echo "Creating directories..."
mkdir -p "$HOME_DIR/imu_calib"
mkdir -p "$HOME_DIR/.ros"
mkdir -p "$WORK_DIR/pioneer_ws/config/nodes"

# Generate individual node parameter files from system config
echo "Generating node parameter files..."

# GPS node parameters
cat > "$WORK_DIR/pioneer_ws/config/nodes/gps_params.yaml" << EOF
# Auto-generated GPS parameters from system config
${ROBOT_ID}_gps1:
  ros__parameters:
    robot_id: "$ROBOT_ID"
    baudrate: $GPS_BAUDRATE
    timeout: $GPS_TIMEOUT
    connection_timeout: $GPS_CONNECTION_TIMEOUT
    retry_delay: $GPS_RETRY_DELAY
    moving_average_rate: $GPS_MOVING_AVG_RATE
    update_rate: $GPS_UPDATE_RATE
    timer_period: $GPS_TIMER_PERIOD
    device_paths: [$GPS_DEVICE_PATHS]
EOF

# Unified IMU node parameters  
cat > "$WORK_DIR/pioneer_ws/config/nodes/imu_params.yaml" << EOF
# Auto-generated unified IMU parameters from system config
${ROBOT_ID}_imu:
  ros__parameters:
    robot_id: "$ROBOT_ID"
    heading_offset: $IMU_HEADING_OFFSET
    connection_timeout: $IMU_CONNECTION_TIMEOUT
    retry_delay: $IMU_RETRY_DELAY
    calibration_file: "$HOME_DIR/$IMU_CALIBRATION_FILE"
    calibFileLoc: "$HOME_DIR/$IMU_CALIBRATION_FILE"
    publish_rate: $IMU_PUBLISH_RATE
    enable_extended_output: $IMU_ENABLE_EXTENDED
    enable_legacy_compatibility: $IMU_ENABLE_LEGACY
EOF

# Pose converter parameters
cat > "$WORK_DIR/pioneer_ws/config/nodes/converter_params.yaml" << EOF
# Auto-generated converter parameters from system config
${ROBOT_ID}_pose_converter:
  ros__parameters:
    robot_id: "$ROBOT_ID"
    timer_period: $POSE_TIMER_PERIOD
    health_check_period: $POSE_HEALTH_CHECK_PERIOD
    reset_timeout: $POSE_RESET_TIMEOUT
EOF

# Locomotion parameters
cat > "$WORK_DIR/pioneer_ws/config/nodes/locomotion_params.yaml" << EOF
# Auto-generated locomotion parameters from system config
${ROBOT_ID}_movebase_kinematics:
  ros__parameters:
    robot_id: "$ROBOT_ID"
    max_vel: $LOCOMOTION_MAX_VEL
    max_vel_open: $LOCOMOTION_MAX_VEL_OPEN
    left_motor_sign: $LOCOMOTION_LEFT_MOTOR_SIGN
    right_motor_sign: $LOCOMOTION_RIGHT_MOTOR_SIGN
    
${ROBOT_ID}_cmd_roboteq:
  ros__parameters:
    robot_id: "$ROBOT_ID"
    serial_port: "$LOCOMOTION_SERIAL_PORT"
    baudrate: $LOCOMOTION_BAUDRATE
    battery_monitoring.enabled: $BATTERY_ENABLED
    battery_monitoring.update_interval: $BATTERY_UPDATE_INTERVAL
EOF

# RF Receiver parameters
cat > "$WORK_DIR/pioneer_ws/config/nodes/rf_receiver_params.yaml" << EOF
${ROBOT_ID}_rf_receiver:
  ros__parameters:
    robot_id: "$ROBOT_ID"
    device_paths: $RF_DEVICE_PATHS
    baudrate: $RF_BAUDRATE
    update_rate: $RF_UPDATE_RATE
    timer_period: $RF_TIMER_PERIOD
    retry_delay: $RF_RETRY_DELAY
    retry_attempts: $RF_RETRY_ATTEMPTS
    pub_topic: "$RF_PUB_TOPIC"
EOF

# Export environment variables for current session
export ROBOT_ID="$ROBOT_ID"
export IMU_OFFSET="$IMU_HEADING_OFFSET"

# Update .bashrc with environment variables
echo "Updating .bashrc..."
BASHRC="$HOME_DIR/.bashrc"

# Remove existing exports
sed -i '/export ROBOT_ID=/d' "$BASHRC" 2>/dev/null || true
sed -i '/export IMU_OFFSET=/d' "$BASHRC" 2>/dev/null || true

# Add new exports
echo "" >> "$BASHRC"
echo "# Pioneer ROS Environment Variables (auto-generated)" >> "$BASHRC"
echo "export ROBOT_ID=$ROBOT_ID" >> "$BASHRC"
echo "export IMU_OFFSET=$IMU_HEADING_OFFSET" >> "$BASHRC"

# Generate enhanced launch file that uses parameter files
LAUNCH_DIR="$WORK_DIR/pioneer_ws/rover_launch/launch"
echo "Generating enhanced launch files..."

cat > "$LAUNCH_DIR/rover_with_params.launch.py" << EOF
import os
from ament_index_python import get_package_share_directory
from launch import LaunchDescription
from launch.actions import IncludeLaunchDescription
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch_ros.actions import Node

def generate_launch_description():
    robot_id = os.getenv("ROBOT_ID", "$ROBOT_ID")
    config_dir = os.path.join(os.getenv("HOME"), "ros2_ws/pioneer_ws/config/nodes")
    
    ld = LaunchDescription()
    
    # GPS node with parameters
    gps_node = Node(
        package="gps_core",
        executable="run_gps1",
        parameters=[os.path.join(config_dir, "gps_params.yaml")],
        output='screen'
    )
    
    # Unified IMU node with parameters
    imu_node = Node(
        package="imu_core",
        executable="run_imu",
        parameters=[os.path.join(config_dir, "imu_params.yaml")],
        output='screen'
    )
    
    # Locomotion nodes with parameters
    movebase_node = Node(
        package="locomotion_core",
        executable=f"movebase_kinematics",
        parameters=[os.path.join(config_dir, "locomotion_params.yaml")],
        output='screen'
    )
    
    cmd_roboteq_node = Node(
        package="locomotion_core",
        executable=f"cmd_roboteq",
        parameters=[os.path.join(config_dir, "locomotion_params.yaml")],
        output='screen'
    )
    
    # Converter node with parameters
    converter_node = Node(
        package="convert_pose",
        executable="converter",
        parameters=[os.path.join(config_dir, "converter_params.yaml")],
        output='screen'
    )

    # RF Receiver node
    rf_receiver_node = Node(
        package="rf_receiver",
        executable="rf_receiver",
        parameters=[os.path.join(config_dir, "rf_receiver_params.yaml")],
        output='screen'
    )
    
    ld.add_action(gps_node)
    ld.add_action(imu_node)
    ld.add_action(movebase_node)
    ld.add_action(cmd_roboteq_node)
    ld.add_action(converter_node)
    ld.add_action(rf_receiver_node)

    return ld
EOF

# Generate startup script
STARTUP_SCRIPT="$WORK_DIR/pioneer_ws/scripts/start_ros2.sh"
echo "Generating startup script: $STARTUP_SCRIPT"

cat > "$STARTUP_SCRIPT" << 'STARTUP_EOF'
#!/bin/bash

# Enhanced startup script with full configuration support
# Robot ID: ROBOT_ID_PLACEHOLDER
# User: USER_NAME_PLACEHOLDER

# Source ROS environment
source /opt/ros/jazzy/setup.bash
source WORK_DIR_PLACEHOLDER/install/setup.bash

# Set environment variables
export ROBOT_ID=ROBOT_ID_PLACEHOLDER
export IMU_OFFSET=IMU_OFFSET_PLACEHOLDER

# Change to workspace directory
cd WORK_DIR_PLACEHOLDER

# Function to verify parameter files exist
verify_param_files() {
    local param_dir="WORK_DIR_PLACEHOLDER/pioneer_ws/config/nodes"
    local required_files=("gps_params.yaml" "imu_params.yaml" "converter_params.yaml" "locomotion_params.yaml")
    
    for file in "${required_files[@]}"; do
        if [ ! -f "$param_dir/$file" ]; then
            echo "Error: Parameter file $file not found"
            echo "Run setup.sh to regenerate parameter files"
            return 1
        fi
    done
    return 0
}

# Function to start node with parameters and retry logic
start_node_with_params() {
    local package=$1
    local executable=$2
    local param_file=$3
    local max_retries=3
    local retry_delay=5
    
    for ((i=1; i<=max_retries; i++)); do
        echo "Starting $package/$executable with params from $param_file (attempt $i/$max_retries)"
        
        if ros2 run $package $executable --ros-args --params-file $param_file; then
            echo "$package/$executable started successfully"
            return 0
        else
            echo "$package/$executable failed to start"
            if [ $i -lt $max_retries ]; then
                echo "Retrying in $retry_delay seconds..."
                sleep $retry_delay
            fi
        fi
    done
    
    echo "Failed to start $package/$executable after $max_retries attempts"
    return 1
}

# Verify parameter files
if ! verify_param_files; then
    echo "Parameter files missing! Running setup to regenerate..."
    cd WORK_DIR_PLACEHOLDER/pioneer_ws/scripts
    ./setup.sh --regen-params-only
fi

# Start launch file with parameters
echo "Starting Pioneer ROS system with full configuration support..."
echo "Robot ID: $ROBOT_ID"
echo "Config directory: WORK_DIR_PLACEHOLDER/pioneer_ws/config/nodes"
echo "Timestamp: $(date)"

# Use the enhanced launch file with parameters
ros2 launch rover_launch rover_with_params.launch.py

STARTUP_EOF

# Replace placeholders in startup script
sed -i "s|ROBOT_ID_PLACEHOLDER|$ROBOT_ID|g" "$STARTUP_SCRIPT"
sed -i "s|USER_NAME_PLACEHOLDER|$USER_NAME|g" "$STARTUP_SCRIPT"
sed -i "s|WORK_DIR_PLACEHOLDER|$WORK_DIR|g" "$STARTUP_SCRIPT"
sed -i "s|IMU_OFFSET_PLACEHOLDER|$IMU_HEADING_OFFSET|g" "$STARTUP_SCRIPT"

chmod +x "$STARTUP_SCRIPT"

# Check which supplementary groups exist
echo "Checking system groups..."
SUPP_GROUPS=""
for group in dialout; do
    if getent group $group > /dev/null 2>&1; then
        echo "  Group '$group' exists"
        SUPP_GROUPS="$SUPP_GROUPS $group"
    else
        echo "  Group '$group' does not exist"
    fi
done

# Add user to necessary groups
echo "Adding user to necessary groups..."
for group in dialout; do
    if getent group $group > /dev/null 2>&1; then
        if ! groups $USER_NAME | grep -q $group; then
            echo "  Adding $USER_NAME to $group group"
            sudo usermod -a -G $group $USER_NAME
        else
            echo "  $USER_NAME is already in $group group"
        fi
    fi
done

# Generate systemd service file with enhanced configuration
SERVICE_NAME=$(read_yaml "$CONFIG_FILE" "service.name")
SERVICE_DESC=$(read_yaml "$CONFIG_FILE" "service.description")
SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}.service"

echo "Generating systemd service file: $SERVICE_FILE"

# Build the service file content
SERVICE_CONTENT="[Unit]
Description=$SERVICE_DESC for $ROBOT_ID
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
Environment=\"ROBOT_ID=$ROBOT_ID\"
Environment=\"IMU_OFFSET=$IMU_HEADING_OFFSET\"
Environment=\"ROS_DOMAIN_ID=0\"
Environment=\"DISPLAY=:0\"
Environment=\"HOME=$HOME_DIR\"
User=$USER_NAME
Group=$USER_NAME
WorkingDirectory=$WORK_DIR
ExecStart=/bin/bash $STARTUP_SCRIPT
Restart=always
RestartSec=10
StandardOutput=journal
StandardError=journal
KillMode=mixed
TimeoutStopSec=30"

# Only add SupplementaryGroups if there are groups to add
if [ -n "$SUPP_GROUPS" ]; then
    SERVICE_CONTENT="$SERVICE_CONTENT
SupplementaryGroups=$SUPP_GROUPS"
fi

SERVICE_CONTENT="$SERVICE_CONTENT

[Install]
WantedBy=multi-user.target"

# Write the service file
echo "$SERVICE_CONTENT" | sudo tee "$SERVICE_FILE" > /dev/null

# Handle --regen-params-only flag
if [ "$1" = "--regen-params-only" ]; then
    echo "Parameter files regenerated successfully"
    exit 0
fi

# Build the workspace
echo "Building workspace..."
cd "$WORK_DIR"

# Clean build if requested
if [ "$1" = "--clean" ]; then
    echo "Performing clean build..."
    rm -rf build install log
fi

# Build with error handling
if colcon build --symlink-install; then
    echo "Build completed successfully"
else
    echo "Build failed!"
    exit 1
fi

# Source the setup file
source install/setup.bash

# Enable and start the service
echo "Setting up systemd service..."
sudo systemctl daemon-reload
sudo systemctl enable "${SERVICE_NAME}.service"

# Ask user if they want to start the service now
read -p "Do you want to start the service now? (y/n): " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    sudo systemctl stop "${SERVICE_NAME}.service" 2>/dev/null || true
    sleep 2
    sudo systemctl start "${SERVICE_NAME}.service"
    sleep 2
    echo "Service status:"
    sudo systemctl status "${SERVICE_NAME}.service" --no-pager
else
    echo "Service not started. You can start it later with:"
    echo "  sudo systemctl start ${SERVICE_NAME}.service"
fi

echo ""
echo "Setup completed successfully!"
echo ""
echo "Configuration Summary:"
echo "  Robot ID: $ROBOT_ID"
echo "  User: $USER_NAME"
echo "  Service: ${SERVICE_NAME}.service"
echo ""
echo "Key Settings Applied:"
echo "  GPS: baudrate=$GPS_BAUDRATE, timeout=$GPS_TIMEOUT, update_rate=${GPS_UPDATE_RATE}Hz"
echo "  IMU: heading_offset=$IMU_HEADING_OFFSET, publish_rate=${IMU_PUBLISH_RATE}Hz, extended=$IMU_ENABLE_EXTENDED" 
echo "  Locomotion: max_vel=$LOCOMOTION_MAX_VEL"
echo "  Monitoring: sensor_timeout=$MONITOR_SENSOR_TIMEOUT"
echo ""
echo "Parameter files generated in: $WORK_DIR/pioneer_ws/config/nodes/"
echo ""
echo "Useful commands:"
echo "  Check service: sudo systemctl status ${SERVICE_NAME}.service"
echo "  View logs: journalctl -u ${SERVICE_NAME}.service -f"
echo "  Rebuild: cd $WORK_DIR && colcon build --symlink-install"
echo "  Regenerate params: cd $WORK_DIR/pioneer_ws/scripts && ./setup.sh --regen-params-only"
echo ""
echo "To change configuration:"
echo "  1. Edit: $CONFIG_FILE"
echo "  2. Run: ./setup.sh --regen-params-only"
echo "  3. Restart: sudo systemctl restart ${SERVICE_NAME}.service"
